name: Infra + Build + Deploy

on:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -reconfigure

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Save EC2 IP
        run: |
          cd terraform
          terraform output -raw ec2_public_ip > ec2_ip.txt

      - name: Upload EC2 IP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ec2-ip-artifact
          path: terraform/ec2_ip.txt

  docker-deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download EC2 IP artifact
        uses: actions/download-artifact@v4
        with:
          name: ec2-ip-artifact
          path: .

      - name: Set EC2 IP
        run: |
          IP=$(grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' ec2_ip.txt | head -n1)
          if [ -z "$IP" ]; then
            echo "EC2 IP not found!" >&2
            exit 1
          fi
          echo "EC2_IP=$IP" >> $GITHUB_ENV
          echo "Using EC2 IP: $IP"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest

      # IMPORTANT â€” wait for EC2 boot
      - name: Wait for EC2 SSH
        run: sleep 70

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 5000:5000 --name node-app ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest
