name: Docker Build & Deploy

on:
  workflow_run:
    workflows: ["Terraform Infra"]   # Trigger after Terraform workflow
    types:
      - completed

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download EC2 IP from Terraform workflow
      - name: Download EC2 IP artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-ip-artifact
          path: .

      - name: Set EC2 IP env
        run: |
          export EC2_IP=$(cat ec2_ip.txt)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: SSH to EC2 and Deploy Node App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-app:latest
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 5000:5000 --name node-app ${{ secrets.DOCKER_USERNAME }}/node-app:latest
