name: Docker Build & Deploy

permissions:
  actions: read
  contents: read
  
on:
  workflow_run:
    workflows: ["Terraform Infra"]
    types:
      - completed

jobs:
  docker-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download EC2 IP artifact
        uses: actions/download-artifact@v4
        with:
          name: ec2-ip-artifact
          path: .

      - name: Set EC2 IP
        run: |
          echo "EC2_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-app:latest
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 5000:5000 --name node-app ${{ secrets.DOCKER_USERNAME }}/node-app:latest
